[package]
name = "psx"
version = "0.1.0"
authors = ["Joe Quigley <quigley.joseph@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4"
log = "0.4"
